# Generated by Django 3.1.7 on 2021-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='upload',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
