# Generated by Django 3.1.7 on 2021-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210316_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataDB',
        ),
    ]
